-- Create user_0d_1 with all privileges on the server.
SET @U0D1_EXISTS = (
	SELECT COUNT(*)
	FROM mysql.user
	WHERE user = 'user_0d_1' AND host = 'localhost'
);

CREATE USER IF NOT EXISTS 'user_0d_1'@'localhost' IDENTIFIED BY 'user_0d_1_pwd';

SET @SQL_GRANT_U0D1 = IF(
	@U0D1_EXISTS = 0,
	"GRANT ALL PRIVILEGES ON *.* TO 'user_0d_1'@'localhost'",
	'DO 0'
);

PREPARE STMT_GRANT_U0D1 FROM @SQL_GRANT_U0D1;
EXECUTE STMT_GRANT_U0D1;
DEALLOCATE PREPARE STMT_GRANT_U0D1;

SET @SQL_REVOKE_U0D1 = IF(
	@U0D1_EXISTS = 0,
	"REVOKE IF EXISTS AUDIT_ABORT_EXEMPT, AUTHENTICATION_POLICY_ADMIN, FIREWALL_EXEMPT, GROUP_REPLICATION_STREAM, PASSWORDLESS_USER_ADMIN, SENSITIVE_VARIABLES_OBSERVER, TELEMETRY_LOG_ADMIN ON *.* FROM 'user_0d_1'@'localhost'",
	'DO 0'
);

PREPARE STMT_REVOKE_U0D1 FROM @SQL_REVOKE_U0D1;
EXECUTE STMT_REVOKE_U0D1;
DEALLOCATE PREPARE STMT_REVOKE_U0D1;
